---

- name: Install packages to allow apt to use a repository over HTTPS
  apt:
    name: "{{ item }}"
    state: present
  with_items:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
    - lsb-core
  become: yes

- name: Add Docker’s official GPG ke
  apt_key:
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: yes

- name: Set up the stable repository.
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  become: yes

- name: Update apt index
  command: apt-get update
  become: yes

- name: Install docker
  apt:
    name: "docker-ce=17.03.0~ce-0~ubuntu-{{ ansible_lsb.codename }}"
    state: present
  become: yes
